// Liste pays pour le dropdown du profil. Format : { code, name, flag }.
// `name` est ce qu'on enregistre dans Firestore (userProfile.country).
export const COUNTRIES = [
  { code: 'SN', name: 'Senegal',              flag: '🇸🇳' },
  { code: 'CA', name: 'Canada',               flag: '🇨🇦' },
  { code: 'FR', name: 'France',               flag: '🇫🇷' },
  { code: 'US', name: 'United States',        flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom',       flag: '🇬🇧' },
  { code: 'CI', name: "Côte d'Ivoire",        flag: '🇨🇮' },
  { code: 'ML', name: 'Mali',                 flag: '🇲🇱' },
  { code: 'MA', name: 'Morocco',              flag: '🇲🇦' },
  { code: 'DZ', name: 'Algeria',              flag: '🇩🇿' },
  { code: 'TN', name: 'Tunisia',              flag: '🇹🇳' },
  { code: 'NG', name: 'Nigeria',              flag: '🇳🇬' },
  { code: 'GH', name: 'Ghana',               flag: '🇬🇭' },
  { code: 'CM', name: 'Cameroon',             flag: '🇨🇲' },
  { code: 'GN', name: 'Guinea',              flag: '🇬🇳' },
  { code: 'BF', name: 'Burkina Faso',         flag: '🇧🇫' },
  { code: 'BJ', name: 'Benin',               flag: '🇧🇯' },
  { code: 'TG', name: 'Togo',                flag: '🇹🇬' },
  { code: 'GA', name: 'Gabon',               flag: '🇬🇦' },
  { code: 'CD', name: 'DR Congo',             flag: '🇨🇩' },
  { code: 'CG', name: 'Congo',               flag: '🇨🇬' },
  { code: 'KE', name: 'Kenya',               flag: '🇰🇪' },
  { code: 'ET', name: 'Ethiopia',             flag: '🇪🇹' },
  { code: 'TZ', name: 'Tanzania',             flag: '🇹🇿' },
  { code: 'UG', name: 'Uganda',              flag: '🇺🇬' },
  { code: 'RW', name: 'Rwanda',              flag: '🇷🇼' },
  { code: 'ZA', name: 'South Africa',         flag: '🇿🇦' },
  { code: 'EG', name: 'Egypt',               flag: '🇪🇬' },
  { code: 'MR', name: 'Mauritania',           flag: '🇲🇷' },
  { code: 'GM', name: 'Gambia',              flag: '🇬🇲' },
  { code: 'GW', name: 'Guinea-Bissau',        flag: '🇬🇼' },
  { code: 'CV', name: 'Cape Verde',           flag: '🇨🇻' },
  { code: 'NE', name: 'Niger',               flag: '🇳🇪' },
  { code: 'TD', name: 'Chad',                flag: '🇹🇩' },
  { code: 'AO', name: 'Angola',              flag: '🇦🇴' },
  { code: 'BE', name: 'Belgium',             flag: '🇧🇪' },
  { code: 'DE', name: 'Germany',             flag: '🇩🇪' },
  { code: 'ES', name: 'Spain',               flag: '🇪🇸' },
  { code: 'IT', name: 'Italy',               flag: '🇮🇹' },
  { code: 'PT', name: 'Portugal',             flag: '🇵🇹' },
  { code: 'NL', name: 'Netherlands',          flag: '🇳🇱' },
  { code: 'CH', name: 'Switzerland',          flag: '🇨🇭' },
  { code: 'SE', name: 'Sweden',              flag: '🇸🇪' },
  { code: 'NO', name: 'Norway',              flag: '🇳🇴' },
  { code: 'DK', name: 'Denmark',             flag: '🇩🇰' },
  { code: 'FI', name: 'Finland',             flag: '🇫🇮' },
  { code: 'IE', name: 'Ireland',             flag: '🇮🇪' },
  { code: 'PL', name: 'Poland',              flag: '🇵🇱' },
  { code: 'RU', name: 'Russia',              flag: '🇷🇺' },
  { code: 'UA', name: 'Ukraine',             flag: '🇺🇦' },
  { code: 'TR', name: 'Turkey',              flag: '🇹🇷' },
  { code: 'GR', name: 'Greece',              flag: '🇬🇷' },
  { code: 'SA', name: 'Saudi Arabia',         flag: '🇸🇦' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'QA', name: 'Qatar',               flag: '🇶🇦' },
  { code: 'KW', name: 'Kuwait',              flag: '🇰🇼' },
  { code: 'LB', name: 'Lebanon',             flag: '🇱🇧' },
  { code: 'JO', name: 'Jordan',              flag: '🇯🇴' },
  { code: 'IL', name: 'Israel',              flag: '🇮🇱' },
  { code: 'IN', name: 'India',               flag: '🇮🇳' },
  { code: 'PK', name: 'Pakistan',             flag: '🇵🇰' },
  { code: 'BD', name: 'Bangladesh',           flag: '🇧🇩' },
  { code: 'CN', name: 'China',               flag: '🇨🇳' },
  { code: 'JP', name: 'Japan',               flag: '🇯🇵' },
  { code: 'KR', name: 'South Korea',          flag: '🇰🇷' },
  { code: 'PH', name: 'Philippines',          flag: '🇵🇭' },
  { code: 'ID', name: 'Indonesia',            flag: '🇮🇩' },
  { code: 'VN', name: 'Vietnam',             flag: '🇻🇳' },
  { code: 'TH', name: 'Thailand',             flag: '🇹🇭' },
  { code: 'MY', name: 'Malaysia',             flag: '🇲🇾' },
  { code: 'SG', name: 'Singapore',            flag: '🇸🇬' },
  { code: 'AU', name: 'Australia',            flag: '🇦🇺' },
  { code: 'NZ', name: 'New Zealand',          flag: '🇳🇿' },
  { code: 'BR', name: 'Brazil',              flag: '🇧🇷' },
  { code: 'AR', name: 'Argentina',            flag: '🇦🇷' },
  { code: 'MX', name: 'Mexico',              flag: '🇲🇽' },
  { code: 'CO', name: 'Colombia',             flag: '🇨🇴' },
  { code: 'CL', name: 'Chile',               flag: '🇨🇱' },
  { code: 'PE', name: 'Peru',                flag: '🇵🇪' },
  { code: 'HT', name: 'Haiti',               flag: '🇭🇹' },
  { code: 'JM', name: 'Jamaica',             flag: '🇯🇲' },
];

export const getCountryByName = (name) =>
  COUNTRIES.find((c) => c.name.toLowerCase() === String(name || '').toLowerCase()) || null;
